name: Renovate

on:
  schedule:
    - cron:  '15 4 * * *'
  
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.2.1
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
